version: '3.4'

services:
  vehicleapi:
    image: vehicleapi
    build:
      context: API
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000